In [1]:
import numpy as np
array = np.arange(20).reshape(4,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [2]:
arr = np.array([9,6,4,8,7,2,3,5,12,20,18,15])
new_array = arr.reshape(2,3,2)
print(new_array)

[[[ 9  6]
  [ 4  8]
  [ 7  2]]

 [[ 3  5]
  [12 20]
  [18 15]]]


In [3]:
x = np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [5]:
ori_arr = np.arange(21,31)
print(ori_arr)
ori_arr = ori_arr[::-1]
print("reverse array: ")
print(ori_arr)

[21 22 23 24 25 26 27 28 29 30]
reverse array: 
[30 29 28 27 26 25 24 23 22 21]


In [6]:
ori_arr = np.ones((5,5))
print(ori_arr)
ori_arr[1:-1,1:-1]=0
print("new_arr:")
print(ori_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
new_arr:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
A = np.random.randint(7,size=(4,4))
A

array([[4, 3, 5, 1],
       [0, 3, 6, 5],
       [0, 1, 6, 5],
       [6, 0, 5, 1]])

In [9]:
B=A[0:1]
B

array([[4, 3, 5, 1]])

In [10]:
C=A[0:2]
C

array([[4, 3, 5, 1],
       [0, 3, 6, 5]])

In [11]:
D=A[2:]
D

array([[0, 1, 6, 5],
       [6, 0, 5, 1]])

In [12]:
A[0:2]*A[2:]

array([[ 0,  3, 30,  5],
       [ 0,  0, 30,  5]])

In [14]:
a = np.random.randint(7,size=(3,4))
b =list(a.sum(axis=1))
print(a)
print("The highest sum column is {}".format(b.index(max(b))))

[[6 3 0 5]
 [5 6 1 5]
 [3 3 5 2]]
The highest sum column is 1
